index:
    path: /
    controller: App\Controller\HomeController::home

curriculum:    
    path: /curriculum
    controller: App\Controller\CurriculumController::home

socialinterview:    
    path: /socialinterview
    controller: App\Controller\SocialinterviewController::index   

stages:    
    path: /stages
    controller: App\Controller\StagesController::index  

generator:    
    path: /generator
    controller: App\Controller\GeneratorController::index

coronavirus:    
    path: /coronavirus
    controller: App\Controller\CoronavirusController::index 